(() => {
    console.log("[Doxmaxima] Altyazı Bulma aktif (Fetch/XHR hook) - YOUTUBE MAIN WORLD");

    const downloadedUrls = new Set();

    function translateViaAI(vttText) {
        return new Promise((resolve) => {
            const requestId = Date.now().toString();
            
            const listener = (event) => {
                if (event.source !== window) return;
                if (event.data && event.data.type === "DOXMAXIMA_TRANSLATE_RESPONSE" && event.data.id === requestId) {
                    window.removeEventListener("message", listener);
                    resolve(event.data.translatedVtt);
                }
            };
            window.addEventListener("message", listener);
            
            window.postMessage({
                type: "DOXMAXIMA_TRANSLATE_REQUEST",
                id: requestId,
                vttText: vttText
            }, "*");
        });
    }

    function handleSubtitleUrl(url) {
        if (!url.includes('/api/timedtext')) return;

        // Otomatik çeviri (tlang) ise alma!
        if (url.includes('tlang=')) {
            console.log("[Doxmaxima] Otomatik çeviri (tlang) algılandı, es geçiliyor.");
            return;
        }

        try {
            const urlObj = new URL(url.startsWith('http') ? url : window.location.origin + url);
            
            const videoId = urlObj.searchParams.get('v') || 'video';
            let lang = urlObj.searchParams.get('lang') || urlObj.searchParams.get('n') || 'altyazi';
            const kind = urlObj.searchParams.get('kind');
            
            const uniqueKey = videoId + '_' + lang + (kind ? '_' + kind : '');

            if (downloadedUrls.has(uniqueKey)) return;
            downloadedUrls.add(uniqueKey);

            // VTT çekmek için
            urlObj.searchParams.set('fmt', 'vtt');
            const downloadUrl = urlObj.toString();

            const filename = `altyazi_${lang}${kind === 'asr' ? '_otomatik' : ''}.vtt`;

            console.log("[Doxmaxima] Seçili altyazı yakalandı, çekiliyor:", filename);

            fetch(downloadUrl)
                .then(res => {
                    if (!res.ok) throw new Error("Ağ hatası");
                    return res.text();
                })
                .then(text => {
                    if (!text || text.trim() === '') return;
                    
                    // Veriyi Content Script'e (altyazı-bulma.js) gönder
                    window.postMessage({
                        type: "DOXMAXIMA_SUBTITLE_DATA",
                        filename: filename,
                        text: text
                    }, "*");
                })
                .catch(err => console.error("[Doxmaxima] İndirme hatası:", err));

        } catch (e) {
            console.error("[Doxmaxima] URL işleme hatası:", e);
        }
    }

    const originalFetch = window.fetch;
    window.fetch = async function(...args) {
        if (!window.location.pathname.startsWith('/watch')) {
            return originalFetch.apply(this, args);
        }

        const url = typeof args[0] === 'string' ? args[0] : (args[0]?.url || '');
        if (url.includes('/api/timedtext')) {
            // Arka planda butondan manuel indirme için VTT linkini oluşturup kaydet
            handleSubtitleUrl(url);

            // Otomatik çeviri (tlang) ise temizleme işlemlerini es geç, orijinalini döndür
            if (url.includes('tlang=')) {
                console.log("[Doxmaxima] Fetch Player: Otomatik çeviri (tlang) algılandı, temizleme es geçiliyor.");
                return originalFetch.apply(this, args);
            }

            // Ekranda (YouTube Player'da) oynayan altyazıya anında müdahale et:
            try {
                if (url.includes('fmt=json3') && window.DoxmaximaSubCleaner) {
                    // Kullanıcının harika tespiti: Orijinal JSON3'ü VTT'ye çevirmek çok riskli ve bozabilir.
                    // O yüzden JSON3'e hiç dokunmuyoruz! YouTube'dan direkt VTT formatını istiyoruz.
                    const urlObj = new URL(url.startsWith('http') ? url : window.location.origin + url);
                    urlObj.searchParams.set('fmt', 'vtt');
                    const vttUrl = urlObj.toString();
                    
                    // VTT'yi arka planda çek
                    const vttResponse = await originalFetch(vttUrl);
                    const vttText = await vttResponse.text();
                    
                    // Altyazı otomatik mi?
                    const isAsr = url.includes('kind=asr') || window.DoxmaximaSubCleaner.isAutoGenerated(vttText);
                    
                    if (isAsr) {
                        // VTT'yi güvenle temizle
                        const cleanResult = window.DoxmaximaSubCleaner.cleanAutoGeneratedVtt(vttText);
                        
                        // AI Çeviriden (Rebuild dahil) geçir (Çeviri kapalıysa orijinalini aynen döner)
                        const translatedVtt = await translateViaAI(cleanResult.text);
                        
                        // Temiz, sorunsuz VTT'yi çok basit ve risksiz bir JSON3'e çevirip YouTube'a yuttur!
                        const cleanJson3 = window.DoxmaximaSubCleaner.vttToJson3(translatedVtt);
                        console.log("[Doxmaxima] Player için VTT çekildi, çeviriden geçirildi ve JSON3'e çevrildi!");
                        
                        return new Response(cleanJson3, {
                            status: 200,
                            headers: { 'content-type': 'application/json' }
                        });
                    } else {
                        // Temizse orijinal isteği yapıp olduğu gibi bırak
                        return await originalFetch.apply(this, args);
                    }
                }
            } catch(e) {
                console.error("[Doxmaxima] Fetch Player müdahale hatası:", e);
            }
        }
        return originalFetch.apply(this, args);
    };

    const originalOpen = XMLHttpRequest.prototype.open;
    const originalSend = XMLHttpRequest.prototype.send;

    XMLHttpRequest.prototype.open = function(method, url, ...rest) {
        this._ytSubUrl = typeof url === 'string' ? url : '';
        return originalOpen.call(this, method, url, ...rest);
    };

    XMLHttpRequest.prototype.send = function(...args) {
        if (!window.location.pathname.startsWith('/watch')) {
            return originalSend.apply(this, args);
        }

        if (this._ytSubUrl && this._ytSubUrl.includes('/api/timedtext')) {
            handleSubtitleUrl(this._ytSubUrl);
            
            // Otomatik çeviri (tlang) ise temizleme işlemlerini es geç, orijinalini döndür
            if (this._ytSubUrl.includes('tlang=')) {
                console.log("[Doxmaxima] XHR Player: Otomatik çeviri (tlang) algılandı, temizleme es geçiliyor.");
                return originalSend.apply(this, args);
            }

            if (this._ytSubUrl.includes('fmt=json3') && window.DoxmaximaSubCleaner) {
                const originalUrl = this._ytSubUrl;
                
                // XHR nesnesini tamamen "Sahte (Mock)" bir duruma alıyoruz.
                // YouTube'un orijinal isteği yapmasını engelleyip, veriyi kendimiz çekip sahte eventlerle yedireceğiz.
                (async () => {
                    try {
                        // 1. Arka planda VTT'yi çek
                        const urlObj = new URL(originalUrl.startsWith('http') ? originalUrl : window.location.origin + originalUrl);
                        urlObj.searchParams.set('fmt', 'vtt');
                        const vttUrl = urlObj.toString();
                        
                        const vttResponse = await originalFetch(vttUrl);
                        const vttText = await vttResponse.text();
                        
                        let responseTextToReturn = "";
                        const isAsr = originalUrl.includes('kind=asr') || window.DoxmaximaSubCleaner.isAutoGenerated(vttText);
                        
                        if (isAsr) {
                            // Temizle ve JSON3'e çevir
                            const cleanResult = window.DoxmaximaSubCleaner.cleanAutoGeneratedVtt(vttText);
                            const translatedVtt = await translateViaAI(cleanResult.text);
                            responseTextToReturn = window.DoxmaximaSubCleaner.vttToJson3(translatedVtt);
                            console.log("[Doxmaxima] (XHR Mock) Player için VTT çekildi, çevirildi ve sahte XHR ile YouTube'a iletildi!");
                        } else {
                            // Altyazı zaten temizse orijinal JSON3 formatını çek ve ver
                            const origResponse = await originalFetch(originalUrl);
                            responseTextToReturn = await origResponse.text();
                            console.log("[Doxmaxima] (XHR Mock) Altyazı temiz, orijinali YouTube'a iletildi.");
                        }

                        // 2. XHR Objesini sahte verilerle doldur
                        Object.defineProperty(this, 'readyState', { get: () => 4 });
                        Object.defineProperty(this, 'status', { get: () => 200 });
                        Object.defineProperty(this, 'statusText', { get: () => 'OK' });
                        Object.defineProperty(this, 'responseText', { get: () => responseTextToReturn });
                        Object.defineProperty(this, 'response', { get: () => responseTextToReturn });
                        
                        this.getAllResponseHeaders = () => 'content-type: application/json\r\n';
                        this.getResponseHeader = (n) => n.toLowerCase() === 'content-type' ? 'application/json' : null;

                        // 3. YouTube Player'ına "İstek Tamamlandı" sinyallerini gönder (Sırasıyla)
                        if (this.onreadystatechange) this.onreadystatechange(new Event('readystatechange'));
                        this.dispatchEvent(new Event('readystatechange'));
                        
                        if (this.onload) this.onload(new Event('load'));
                        this.dispatchEvent(new Event('load'));
                        
                        if (this.onloadend) this.onloadend(new ProgressEvent('loadend'));
                        this.dispatchEvent(new ProgressEvent('loadend'));

                    } catch(e) {
                        console.error("[Doxmaxima] XHR Mock hatası (Yedek sisteme geçiliyor):", e);
                        // Eğer bizim sahte sistem çökerse bari orijinal istek gitsin diye
                        originalSend.apply(this, args);
                    }
                })();
                
                // Orijinal XHR isteğini KESİNLİKLE durduruyoruz (return ile çıkıyoruz)
                return;
            }
        }
        return originalSend.apply(this, args);
    };
})();
