console.log("[Doxmaxima] Altyazı İndirme Scripti Yüklendi (Content Script)");

// 2. Interceptor'dan gelen veriyi dinleyip hafızada tutuyoruz
let sonAltyaziVerisi = null;

window.addEventListener("message", (event) => {
    // Sadece aynı sayfadan gelen mesajları kabul et
    if (event.source !== window) return;

    // Mesaj tipi bizim gönderdiğimiz tip ise
    if (event.data && event.data.type === "DOXMAXIMA_SUBTITLE_DATA") {
        sonAltyaziVerisi = {
            text: event.data.text,
            filename: event.data.filename
        };
        console.log("[Doxmaxima] Altyazı hafızaya alındı, butona basılınca indirilecek:", sonAltyaziVerisi.filename);
    }
});

// 3. Popup'tan (ui.html) gelen indirme isteğini dinliyoruz
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === "DOWNLOAD_SUBTITLE_MANUAL" || request.type === "DOWNLOAD_SUBTITLE_CLEAN") {
        if (!sonAltyaziVerisi) {
            alert("Lütfen önce videodan bir altyazı seçin veya altyazıyı açın.");
            return;
        }

        let fileText = sonAltyaziVerisi.text;
        let fileName = sonAltyaziVerisi.filename;

        // Temizlenmiş indirme isteniyorsa temizleme algoritmasını çalıştır
        if (request.type === "DOWNLOAD_SUBTITLE_CLEAN") {
            if (window.DoxmaximaSubCleaner) {
                const result = window.DoxmaximaSubCleaner.cleanAutoGeneratedVtt(fileText);
                fileText = result.text;
                
                if (result.wasAlreadyClean) {
                    alert("Bu altyazı zaten yayıncı tarafından temiz/manuel olarak eklenmiş. Orijinal haliyle indiriliyor.");
                } else {
                    fileName = fileName.replace('.vtt', '_temizlenmis.vtt');
                    console.log("[Doxmaxima] Altyazı başarıyla temizlendi.");
                }
            } else {
                console.error("[Doxmaxima] Temizleme motoru bulunamadı!");
                alert("Temizleme sistemi şu an kullanılamıyor, sayfayı yenileyin.");
                return;
            }
        }

        console.log("[Doxmaxima] Butona basıldı, indiriliyor:", fileName);

        const blob = new Blob([fileText], { type: 'text/vtt' });
        const blobUrl = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = blobUrl;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(blobUrl);
    }
});
